### ISSUE TITLE
Mobiltelefonnummer

### ISSUE THREAD

**Issue by davidak** [davidak/PyZufall#26]
Vorwahlen + zufällige Zahl

Benötigt von: https://github.com/davidak/random-vcard-generator/issues/8

**Comment by Fruitseller** [comment]
Ich habe mir `vcardgen` geforked und schnell ein Rufnummernfeld mit völlig zufälligen Zahlen generiert.
Hast du noch Interesse an den Projekt? Dann könnte ich schauen, dass ich es hier einbaue.

**Comment by davidak** [comment]
@Fruitseller generell ja, nur momentan wenig Zeit.

Du kannst gerne ein Pull Request erstellen, dann schaue ich es mir an. Es sollten aber plausible Nummern sein, also mit Vorwahl deutscher Provider.
